### ISSUE TITLE
Missing deploy instructions

### ISSUE THREAD

**Issue by ofarukcaki** [OFarukCaki/All-in-One-Crypto-Market-API#1]
It is needed to be a guide about how to deploy ASP.NET Core application. Please create a simple guide about it on Readme.md. Thanks for your contributions.

**Comment by CSJedi** [comment]
Hi, guide, how deploy ASP.NET Core to IIS will suit for you?

**Comment by ofarukcaki** [comment]
@CSJedi I also could available alongside with other(Nginx). Please send a pull request that.
