### ISSUE TITLE
Create CONTRIBUTE.md

### ISSUE THREAD

**Issue by ofarukcaki** [OFarukCaki/All-in-One-Crypto-Market-API#2]
Create CONTRIBUTE.md as a guide for contributors.

**Comment by 0x48piraj** [comment]
**Working on it !!**
Should I just Add a **blank file** ?
Or, with some **specs** ? 
`if True:`
**Any templates, examples, ref(s)** ?

**Comment by ofarukcaki** [comment]
It should have at least some simple instructions, shouldn't be blank. Thanks!

**Comment by 0x48piraj** [comment]
Can you give me some examples or some sample instructions ?
Or, I should implement **Github's general contribution rules** ?

**Comment by ofarukcaki** [comment]
Nothing on my mind. But general rules would be appreciated

**Comment by 0x48piraj** [comment]
Aye Aye Captain ! :wink:
